import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { ProductCard } from '../components/ProductCard'
import { getCachedProducts, getProducts } from '../lib/api'
import type { Product } from '../types'

export function HomePage() {
  const [products, setProducts] = useState<Product[]>(() => getCachedProducts())
  useEffect(() => { void getProducts().then(setProducts) }, [])
  const featuredProducts = useMemo(() => products.filter((product) => product.featured), [products])
  return <>
    <section className="legacy-hero home-hero"><div className="legacy-hero-text"><h1>Révélez votre éclat avec du maquillage de haute qualité</h1><p>Des textures luxueuses, des pigments intenses et des formules reconnues, soigneusement sélectionnés parmi les meilleures marques internationales.</p><div className="legacy-cta"><Link className="legacy-btn primary" to="/boutique">Découvrir la boutique</Link><a className="legacy-btn secondary" href="#produits">Voir nos essentiels</a></div></div></section>
    <section id="produits" className="legacy-section"><h2 className="legacy-section-title">Nos essentiels stars</h2><p className="legacy-subtitle">Des classiques indémodables aux dernières pépites backstage : tout pour un look impeccable du matin au soir.</p><div className="legacy-product-grid">{featuredProducts.map((product) => <ProductCard key={product.id} product={product} />)}</div><article className="discover-banner"><div className="discover-banner-copy"><span className="legacy-tag">Nouveautés</span><h3>Envie d’en voir encore plus ?</h3><p>Plongez dans notre boutique complète pour découvrir toutes les gammes, teintes et exclusivités.</p></div><Link className="discover-banner-button" to="/boutique">Découvrir notre boutique</Link></article></section>
    <section id="collections" className="legacy-section"><h2 className="legacy-section-title">Collections signature</h2><p className="legacy-subtitle">Des univers pensés pour répondre aux besoins de chaque peau et révéler toutes les beautés.</p><div className="legacy-collections-grid"><article className="legacy-card"><span className="legacy-tag">Glow couture</span><h3>Éclat instantané</h3><p>Des produits lumineux pour un teint frais et éclatant, choisis parmi les marques les plus prisées du moment.</p></article><article className="legacy-card"><span className="legacy-tag">Studio Pro</span><h3>Résistance 24/7</h3><p>Maquillage professionnel importé, testé pour une tenue longue durée, parfait pour les journées actives et les soirées glamour.</p></article><article className="legacy-card"><span className="legacy-tag">Clean Beauty</span><h3>Beauté naturelle</h3><p>Une collection importée de produits à base d’ingrédients naturels, alliant douceur, qualité et respect de la peau.</p></article></div></section>
    <section id="valeurs" className="legacy-section"><h2 className="legacy-section-title">Nos engagements beauté</h2><div className="legacy-values"><div><span>01</span><article><h3>Produits authentiques et sûrs</h3><p>Tous nos produits sont 100 % originaux et testés dermatologiquement pour convenir même aux peaux sensibles.</p></article></div><div><span>02</span><article><h3>Qualité premium garantie</h3><p>Nous sélectionnons uniquement des marques reconnues pour leurs formules performantes, leurs textures agréables et leurs résultats professionnels.</p></article></div><div><span>03</span><article><h3>Beauté éthique et responsable</h3><p>Aucun test sur les animaux. Nous privilégions des marques engagées dans une production respectueuse du vivant et de l’environnement.</p></article></div></div></section>
    <section className="legacy-section"><h2 className="legacy-section-title">Questions fréquentes</h2><div className="legacy-faq"><article><h3>Quels sont vos délais de livraison ?</h3><p>Nos délais sont de 24 à 48 h sur Alger et de 2 à 3 jours ouvrables dans les autres wilayas.</p></article><article><h3>Quels moyens de paiement acceptez-vous ?</h3><p>Vous pouvez payer à la livraison. D’autres modes sont disponibles comme BaridiMob et CIB.</p></article><article><h3>Comment être sûre de la qualité ?</h3><p>Tous nos produits sont 100 % authentiques et soigneusement sélectionnés auprès de fournisseurs de confiance.</p></article></div></section>
  </>
}
